//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   xyzw        0     NONE   float   xyzw
// TEXCOORD                 0   xyzw        1     NONE   float   xyzw
// TEXCOORD                 1   xyzw        2     NONE   float       
// NORMAL                   0   xyzw        3     NONE   float   xyzw
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float   xyzw
// TEXCOORD                 0   xyzw        1     NONE   float   xyzw
// TEXCOORD                 1   xyzw        2     NONE   float   xyzw
// TEXCOORD                 2   xyz         3     NONE   float   xyz 
// TEXCOORD                 3   xyz         4     NONE   float   xyz 
// TEXCOORD                 4   xyzw        5     NONE   float   xyzw
// NORMAL                   0   xyzw        6     NONE   float   xyzw
//
      vs_4_0
      dcl_constantbuffer CB0[11], immediateIndexed
      dcl_constantbuffer CB1[5], immediateIndexed
      dcl_constantbuffer CB2[7], immediateIndexed
      dcl_constantbuffer CB3[21], immediateIndexed
      dcl_sampler s0, mode_default
      dcl_resource_texture2d (float,float,float,float) t0
      dcl_input v0.xyzw
      dcl_input v1.xyzw
      dcl_input v3.xyzw
      dcl_output_siv o0.xyzw, position
      dcl_output o1.xyzw
      dcl_output o2.xyzw
      dcl_output o3.xyz
      dcl_output o4.xyz
      dcl_output o5.xyzw
      dcl_output o6.xyzw
      dcl_temps 9
   0: mul r0.xyz, cb2[0].yyyy, cb3[10].xyzx
   1: mad r0.xyz, cb3[9].xyzx, cb2[0].xxxx, r0.xyzx
   2: mad r0.xyz, cb3[11].xyzx, cb2[0].zzzz, r0.xyzx
   3: mad r0.xyz, cb3[12].xyzx, cb2[0].wwww, r0.xyzx
   4: mul r1.xyz, cb2[1].yyyy, cb3[10].xyzx
   5: mad r1.xyz, cb3[9].xyzx, cb2[1].xxxx, r1.xyzx
   6: mad r1.xyz, cb3[11].xyzx, cb2[1].zzzz, r1.xyzx
   7: mad r1.xyz, cb3[12].xyzx, cb2[1].wwww, r1.xyzx
   8: mul r2.xyz, cb2[2].yyyy, cb3[10].xyzx
   9: mad r2.xyz, cb3[9].xyzx, cb2[2].xxxx, r2.xyzx
  10: mad r2.xyz, cb3[11].xyzx, cb2[2].zzzz, r2.xyzx
  11: mad r2.xyz, cb3[12].xyzx, cb2[2].wwww, r2.xyzx
  12: mul r3.xyz, cb2[3].yyyy, cb3[10].xyzx
  13: mad r3.xyz, cb3[9].xyzx, cb2[3].xxxx, r3.xyzx
  14: mad r3.xyz, cb3[11].xyzx, cb2[3].zzzz, r3.xyzx
  15: mad r3.xyz, cb3[12].xyzx, cb2[3].wwww, r3.xyzx
  16: mul r0.w, cb0[8].y, cb1[0].x
  17: mul r0.w, r0.w, l(60.000000)
  18: sincos r4.x, r5.x, r0.w
  19: add r0.w, r4.x, l(1.000000)
  20: mul r1.w, r5.x, cb0[6].y
  21: mul r0.w, r0.w, cb0[6].w
  22: mad r4.xy, v1.xyxx, r1.wwww, r0.wwww
  23: sample_l r4.xyzw, r4.xyxx, t0.xyzw, s0, l(0.000000)
  24: ftoi r0.w, cb0[10].x
  25: mul r4.yzw, cb1[0].xxyz, l(0.000000, 0.100000, 0.100000, 0.100000)
  26: mov r5.xy, v1.xyxx
  27: mov r5.z, l(0)
  28: mov r6.xyz, l(0,0,0,0)
  29: mov r1.w, r0.w
  30: loop 
  31:   ige r2.w, l(0), r1.w
  32:   breakc_nz r2.w
  33:   round_ni r7.xyz, r5.xyzx
  34:   mul r8.xyz, r4.yzwy, r7.xyzx
  35:   mad r7.xyz, r7.xxzx, r7.yyyy, r8.xyzx
  36:   sincos r7.xyz, null, r7.xyzx
  37:   add r6.xyz, r6.xyzx, r7.xyzx
  38:   mul r5.xyz, r5.xyzx, l(2.500000, 2.500000, 2.500000, 0.000000)
  39:   iadd r1.w, r1.w, l(-1)
  40: endloop 
  41: mul r4.yz, cb0[7].yyxy, l(0.000000, 0.001000, 0.100000, 0.000000)
  42: mul r5.xyz, r4.yyyy, r6.xyzx
  43: mul r4.yzw, r4.zzzz, r5.xxyz
  44: mul r4.xyz, r4.xxxx, r4.yzwy
  45: mul r4.x, r4.x, cb0[8].w
  46: mul r4.y, r4.y, cb0[9].x
  47: mul r4.xyz, r4.xyzx, v3.xyzx
  48: mad r4.xyz, r4.xyzx, l(10.000000, 10.000000, 10.000000, 0.000000), v0.xyzx
  49: mul r5.xyzw, r4.yyyy, cb2[1].xyzw
  50: mad r5.xyzw, cb2[0].xyzw, r4.xxxx, r5.xyzw
  51: mad r4.xyzw, cb2[2].xyzw, r4.zzzz, r5.xyzw
  52: add r5.xyzw, r4.xyzw, cb2[3].xyzw
  53: mul r6.xyzw, r5.yyyy, cb3[18].xyzw
  54: mad r6.xyzw, cb3[17].xyzw, r5.xxxx, r6.xyzw
  55: mad r6.xyzw, cb3[19].xyzw, r5.zzzz, r6.xyzw
  56: mad o0.xyzw, cb3[20].xyzw, r5.wwww, r6.xyzw
  57: mad r4.xyz, cb2[3].xyzx, v0.wwww, r4.xyzx
  58: mul r1.xyz, r1.xyzx, v3.yyyy
  59: mad r0.xyz, r0.xyzx, v3.xxxx, r1.xyzx
  60: mad r0.xyz, r2.xyzx, v3.zzzz, r0.xyzx
  61: mad r0.xyz, r3.xyzx, v3.wwww, r0.xyzx
  62: dp3 r0.z, r0.xyzx, r0.xyzx
  63: rsq r0.z, r0.z
  64: mul r0.xy, r0.zzzz, r0.xyxx
  65: dp3 r1.x, v3.xyzx, cb2[4].xyzx
  66: dp3 r1.y, v3.xyzx, cb2[5].xyzx
  67: dp3 r1.z, v3.xyzx, cb2[6].xyzx
  68: dp3 r0.z, r1.xyzx, r1.xyzx
  69: rsq r0.z, r0.z
  70: mul r1.xyz, r0.zzzz, r1.xyzx
  71: mad o3.xy, r0.xyxx, l(0.500000, 0.500000, 0.000000, 0.000000), l(0.500000, 0.500000, 0.000000, 0.000000)
  72: add r0.xyz, r4.xyzx, -cb1[4].xyzx
  73: dp3 r0.w, r0.xyzx, r0.xyzx
  74: rsq r0.w, r0.w
  75: mul r0.xyz, r0.wwww, r0.xyzx
  76: dp3 r0.x, r0.xyzx, r1.xyzx
  77: add r0.x, r0.x, cb0[8].z
  78: mul r0.y, cb0[7].w, cb0[7].z
  79: log r0.x, r0.x
  80: mul r0.x, r0.x, cb0[8].x
  81: exp r0.x, r0.x
  82: mul o5.x, r0.x, r0.y
  83: mov o1.xyzw, v1.xyzw
  84: mov o2.xyzw, l(0,0,0,0)
  85: mov o5.yzw, l(0,0,0,0)
  86: mov o6.xyzw, l(0,0,0,0)
  87: mov o3.z, l(0)
  88: mov o4.xyz, r1.xyzx
  89: ret 
// Approximately 0 instruction slots used
