//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float       
// TEXCOORD                 0   xyzw        1     NONE   float   xy  
// TEXCOORD                 1   xyzw        2     NONE   float       
// TEXCOORD                 2   xyz         3     NONE   float   xy  
// TEXCOORD                 3   xyz         4     NONE   float       
// TEXCOORD                 4   xyzw        5     NONE   float   x   
// NORMAL                   0   xyzw        6     NONE   float       
// SV_IsFrontFace           0   x           7    FFACE    uint       
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
//
      ps_4_0
      dcl_constantbuffer CB0[12], immediateIndexed
      dcl_constantbuffer CB1[1], immediateIndexed
      dcl_sampler s0, mode_default
      dcl_sampler s1, mode_default
      dcl_sampler s2, mode_default
      dcl_sampler s3, mode_default
      dcl_resource_texture2d (float,float,float,float) t0
      dcl_resource_texture2d (float,float,float,float) t1
      dcl_resource_texture2d (float,float,float,float) t2
      dcl_resource_texture2d (float,float,float,float) t3
      dcl_input_ps linear v1.xy
      dcl_input_ps linear v3.xy
      dcl_input_ps linear v5.x
      dcl_output o0.xyzw
      dcl_temps 6
   0: mul r0.x, cb0[8].y, cb1[0].x
   1: mul r0.xyz, r0.xxxx, l(30.000000, 60.000000, 120.000000, 0.000000)
   2: sincos r1.x, r2.x, r0.y
   3: add r0.y, r1.x, l(1.000000)
   4: mul r1.yz, r0.xxxx, cb0[5].zzwz
   5: mad r1.yz, v1.xxyx, cb0[5].xxyx, r1.yyzy
   6: sample r3.xyzw, r1.yzyy, t0.xyzw, s2
   7: mul r0.w, r2.x, cb0[6].y
   8: mul r0.y, r0.y, cb0[6].w
   9: mad r0.yw, v1.xxxy, r0.wwww, r0.yyyy
  10: sample r2.xyzw, r0.ywyy, t1.xyzw, s3
  11: eq r0.yw, cb0[11].yyyy, l(0.000000, 0.000000, 0.000000, 1.000000)
  12: if_nz r0.y
  13:   mad r1.yz, v3.xxyx, cb0[4].yyyy, cb0[4].wwww
  14:   sample r4.xyzw, r1.yzyy, t2.xyzw, s1
  15: else 
  16:   mov r4.xyzw, l(0,0,0,0)
  17: endif 
  18: if_nz r0.w
  19:   sample r4.xyzw, v1.xyxx, t3.xyzw, s0
  20: endif 
  21: mul r0.y, r2.x, r3.x
  22: sincos r0.xz, null, r0.xxzx
  23: mul r0.xz, r0.xxzx, r0.yyyy
  24: mul r0.w, r0.x, v1.x
  25: mad r1.yz, r0.wwww, cb0[7].xxxx, v1.xxyx
  26: ftoi r0.w, cb0[10].x
  27: mul r2.xy, cb1[0].xyxx, l(0.100000, 0.100000, 0.000000, 0.000000)
  28: mov r2.zw, r1.yyyz
  29: mov r3.xy, l(0,0,0,0)
  30: mov r1.w, r0.w
  31: loop 
  32:   ige r3.z, l(0), r1.w
  33:   breakc_nz r3.z
  34:   round_ni r3.zw, r2.zzzw
  35:   mul r5.xy, r2.xyxx, r3.zwzz
  36:   mad r3.zw, r3.zzzz, r3.wwww, r5.xxxy
  37:   sincos r3.zw, null, r3.zzzw
  38:   add r3.xy, r3.zwzz, r3.xyxx
  39:   mul r2.zw, r2.zzzw, l(0.000000, 0.000000, 2.500000, 2.500000)
  40:   iadd r1.w, r1.w, l(-1)
  41: endloop 
  42: mul r1.yz, r3.xxyx, cb0[9].yyyy
  43: mul r0.xyz, r0.xyzx, r1.yxyy
  44: mul r0.y, r1.z, r0.y
  45: mul r0.xyz, r0.xyzx, cb0[7].xxxx
  46: mad r1.y, r0.y, l(0.375000), cb0[2].y
  47: mad r1.xz, r0.xxzx, l(0.187500, 0.000000, 0.750000, 0.000000), cb0[2].xxzx
  48: mul r4.w, r4.w, cb0[9].w
  49: mul r0.xyzw, r4.xyzw, cb0[3].xyzw
  50: eq r1.w, cb0[9].z, l(1.000000)
  51: add r2.x, r1.y, r1.x
  52: add r2.x, r1.z, r2.x
  53: add r2.y, r0.y, r0.x
  54: mad r2.y, r4.z, cb0[3].z, r2.y
  55: mul r2.xy, r2.xyxx, l(0.333333, 0.333333, 0.000000, 0.000000)
  56: movc r0.xyz, r1.wwww, r2.yyyy, r0.xyzx
  57: movc r1.xyz, r1.wwww, r2.xxxx, r1.xyzx
  58: add r1.xyz, -r0.xyzx, r1.xyzx
  59: add r1.w, -r0.w, cb0[2].w
  60: mad o0.xyzw, v5.xxxx, r1.xyzw, r0.xyzw
  61: ret 
// Approximately 0 instruction slots used
