namespace Parser.DXBC.Instructions;

public enum Opcode
{
    Unknown,

    Add,
    And,
    Break,
    BreakC,
    Call,
    CallC,
    Case,
    Continue,
    ContinueC,
    Cut,
    Default,
    DerivRtx,
    DerivRty,
    Discard,
    Div,
    Dp2,
    Dp3,
    Dp4,
    Else,
    Emit,
    EmitThenCut,
    EndIf,
    EndLoop,
    EndSwitch,
    Eq,
    Exp,
    Frc,
    Ftoi,
    Ftou,
    Itof,
    Utof,
    GE,
    IAdd,
    If,
    IEq,
    IGe,
    ILt,
    INeg,
    IMad,
    IMax,
    IMin,
    IMul,
    INe,
    Label,
    Ld,
    Log,
    Loop,
    Lt,
    Mad,
    Min,
    Max,
    Mov,
    MovC,
    Mul,
    Ne,
    Nop,
    Not,
    Or,
    ResInfo,
    Ret,
    Retc,
    RoundNE,
    RoundNI,
    RoundPI,
    RoundZ,
    Rsq,
    Rcp,
    Sample,
    SampleL,
    SampleC,
    SampleCLZ,
    SampleB,
    SampleD,
    Sqrt,
    Switch,
    SinCos,
    Dp2Add,
    DclResource,
    DclSampler,
    DclConstantBuffer,
    DclInput,
    DclInputPS,
    DclOutput,
    DclTemps,
    DclGlobalFlags,
    DclInputSVG,
    DclOutputSIV,

    // ===================== previously missing arithmetic/bitwise/comparison =====================

    ISub,
    UMul,
    UMad,
    UDiv,
    UMin,
    UMax,
    Xor,
    Ishl,
    Ushr,
    Ishr,
    CountBits,
    FirstBitHi,
    FirstBitLo,
    FirstBitSHi,
    ReverseBits,
    Bfi,
    Ubfe,
    Ibfe,
    Le,
    Gt,
    Uge,
    Ult,
    Ugt,
    Ule,
    Any,
    All,

    // ===================== conversions =====================

    F16ToF32,
    F32ToF16,
    BitcastFloat,
    BitcastInt,
    BitcastUInt,

    // ===================== extended math =====================
    
    MSad,
    Dst,
    Mul64,
    UMul64,
    AddSat,
    MulSat,
    MadSat,

    // ===================== texture / buffer =====================

    LdMS,
    SampleInfo,
    SamplePos,
    SampleIndex,
    CheckAccessFullyMapped,
    Gather4,
    Gather4C,
    Gather4Po,
    Gather4PoC,
    Lod,
    BufInfo,
    LdUAVTyped,
    LdRaw,
    LdStructured,
    StoreRaw,
    StoreStructured,
    StoreUAV,
    SamplePo,
    SamplePoC,

    // ===================== declarations =====================

    DclUAV,
    DclThreadGroup,
    DclIndexRange,
    DclFunctionBody,
    DclFunctionTable,
    DclIndexableTemp,
    DclStream,
    DclInterface,
    DclInputControlPointCount,
    DclOutputControlPointCount,
    DclHSMaxTessFactor,
    DclDomain,
    DclPartitioning,
    DclOutputTopology,

    // ===================== previously missing SM5 declarations/atomics =====================

    DclTessOutputPrimitive,
    DclHSForkPhaseInstanceCount,
    DclHSJoinPhaseInstanceCount,
    DclUAVRaw,
    DclUAVStructured,
    DclTGSMRaw,
    DclTGSMStructured,
    DclResourceRaw,
    DclResourceStructured,
    ImmAtomicAlloc,
    ImmAtomicConsume,
    DclGSInstanceCount,

    // ===================== UAV atomics =====================

    AtomicIAdd,
    AtomicAnd,
    AtomicOr,
    AtomicXor,
    AtomicIMin,
    AtomicIMax,
    AtomicUMin,
    AtomicUMax,
    AtomicCmpStore,
    ImmAtomicIAdd,
    ImmAtomicAnd,
    ImmAtomicOr,
    ImmAtomicXor,
    ImmAtomicIMin,
    ImmAtomicIMax,
    ImmAtomicUMin,
    ImmAtomicUMax,
    ImmAtomicExch,
    ImmAtomicCmpExch,

    // ===================== synchronization =====================

    Sync,
    GroupMemoryBarrier,
    GroupMemoryBarrierWithGroupSync,
    DeviceMemoryBarrier,
    DeviceMemoryBarrierWithGroupSync,
    AllMemoryBarrier,
    AllMemoryBarrierWithGroupSync,

    // ===================== geometry shader =====================

    EmitStream,
    CutStream,
    EmitThenCutStream,

    // ===================== hull shader =====================

    HSControlPointPhase,
    HSForkPhase,
    HSJoinPhase,

    // ===================== dynamic linkage =====================

    InterfaceCall,
    InterfaceCallC,

    // ===================== double precision =====================

    DMov,
    DMovC,
    DAdd,
    DMax,
    DMin,
    DMul,
    DEq,
    DGe,
    DLt,
    DNe,
    DSub,
    DDiv,
    DFma,
    DRcp,
    DSqrt,
    DRsq,
    DtoI,
    DtoU,
    ItoD,
    UtoD,
    FtoD,
    DtoF,
    // ===================== SM5.1 / misc additions =====================

    CustomData,

    DerivRtxCoarse,
    DerivRtxFine,
    DerivRtyCoarse,
    DerivRtyFine,

    UAddC,
    USubB,
    SwapC,

    EvalSnapped,
    EvalSampleIndex,
    EvalCentroid,
    
    // IR-only operations
    Sub,
    Neg,
    Abs,
    Pow,
    Lrp,
    Saturate,
}